-- **************************************************************************************************************
-- *  AUTHOR:       JONATHAN MENDOZA                                                                            *
-- *  NAME:         DDL_SCHEMA AUTH                                                                             *
-- *  DATE:         2020-07                                                                                     *
-- *  DESCRIPTION:  SEQUENCE OF SQL SENTENCES TO GENERATE THE AUTH SCHEMA                                       *
-- *  VERSION:      v1.0                                                                                        *
-- **************************************************************************************************************

------------------------------------------------------------------------------------
-- DDL for ALTER DATABASE
------------------------------------------------------------------------------------
--ALTER DATABASE "wallet-zelle" SET datestyle TO "SQL, DMY";

------------------------------------------------------------------------------------
-- DDL for SCHEMA AUTH
------------------------------------------------------------------------------------
CREATE SCHEMA AUTH;

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
-- DDL for TABLE AUTH.ROLE
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

-- DROP TABLE AUTH.ROLE;

CREATE TABLE AUTH.ROLE(
    R_ID_PK     serial        NOT NULL,
    R_NAME      varchar(100)  NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (R_ID_PK)
);

COMMENT ON TABLE AUTH.ROLE 		    IS 'Stores the existing roles in the application and that allow its navigation.';
COMMENT ON COLUMN AUTH.ROLE.R_ID_PK IS 'ID autogenerated by the DB to uniquely identify the defined role. Primary key.';
COMMENT ON COLUMN AUTH.ROLE.R_NAME 	IS 'Name of the role, which complies with the established nomenclature of the prefix (ROLE_). Example: ROLE_ADMIN, ROLE_USER.';

-----------------------------------------------------------------------------------
-- DDL for CONTRAINST OF THE UNIQUE
-----------------------------------------------------------------------------------
ALTER TABLE AUTH.ROLE   ADD CONSTRAINT R_NAME_UQ    UNIQUE (R_NAME);

------------------------------------------------------------------------------------
-- DDL for CREATE SEQUENCE (ROLE)
------------------------------------------------------------------------------------

/*CREATE SEQUENCE AUTH.ROLE_R_ID_PK_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;*/

------------------------------------------------------------------------------------
-- DML for TABLE AUTH.ROLE
------------------------------------------------------------------------------------
INSERT INTO AUTH.ROLE(R_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTH.ROLE(R_NAME) VALUES ('ROLE_USER');

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
-- DDL for TABLE AUTH.CUSTOMER
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

-- DROP TABLE AUTH.CUSTOMER;

CREATE TABLE AUTH.CUSTOMER(
    C_ID_PK         BIGSERIAL     NOT NULL,
    C_FIRST_NAME    VARCHAR(250)  NOT NULL,
    C_LAST_NAME     VARCHAR(250)  NOT NULL,
    C_EMAIL         VARCHAR(250)  NOT NULL,
    C_PASS          VARCHAR(250)  NOT NULL,
    C_CREATED_AT    TIMESTAMP WITHOUT TIME ZONE,
    C_UPDATED_AT    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (C_ID_PK)
);

COMMENT ON TABLE AUTH.CUSTOMER 			      IS 'Stores all the data of the user registered on the platform.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_ID_PK       IS 'ID autogenerated by the DB that uniquely identifies the registered user. Primary key.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_FIRST_NAME  IS 'First name of the user.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_LAST_NAME   IS 'Last name of the user.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_EMAIL       IS 'Email associated with the user. Unique field.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_PASS 	      IS 'Password of the user account.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_CREATED_AT  IS 'Date of creation.';
COMMENT ON COLUMN AUTH.CUSTOMER.C_UPDATED_AT  IS 'Update date.';

-----------------------------------------------------------------------------------
-- DDL for CONTRAINST OF THE UNIQUE
-----------------------------------------------------------------------------------
ALTER TABLE AUTH.CUSTOMER   ADD CONSTRAINT C_EMAIL_UQ       UNIQUE (C_EMAIL);

------------------------------------------------------------------------------------
-- DDL for INDEXES
------------------------------------------------------------------------------------
CREATE INDEX C_EMAIL_INDX  ON AUTH.CUSTOMER(C_EMAIL);

------------------------------------------------------------------------------------
-- DDL for CREATE SEQUENCE (CUSTOMER)
------------------------------------------------------------------------------------

/*CREATE SEQUENCE AUTH.CUSTOMER_C_ID_PK_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;*/

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
-- DDL FOR TABLE AUTH.CUSTOMER_ROLE
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

-- DROP TABLE AUTH.CUSTOMER_ROLE;

CREATE TABLE AUTH.CUSTOMER_ROLE(
	C_ID_PFK 	INT 	NOT NULL,
	R_ID_PFK 	INT 	NOT NULL,
	CONSTRAINT CUSTOMER_ROLE_PK PRIMARY KEY (C_ID_PFK,R_ID_PFK)
);

COMMENT ON TABLE AUTH.CUSTOMER_ROLE 		  IS 'Stores the roles assigned by each user.';
COMMENT ON COLUMN AUTH.CUSTOMER_ROLE.C_ID_PFK IS 'ID that uniquely identifies the registered user. Foreign key.';
COMMENT ON COLUMN AUTH.CUSTOMER_ROLE.R_ID_PFK IS 'ID autogenerated by the DB that uniquely identifies the user. Foreign key.';

------------------------------------------------------------------------------------
-- DDL FOR CONTRAINST OF THE FOREIGN KEY
------------------------------------------------------------------------------------
ALTER TABLE AUTH.CUSTOMER_ROLE     ADD CONSTRAINT C_ID_FK    FOREIGN KEY (C_ID_PFK)     REFERENCES AUTH.CUSTOMER (C_ID_PK);
ALTER TABLE AUTH.CUSTOMER_ROLE     ADD CONSTRAINT R_ID_FK    FOREIGN KEY (R_ID_PFK)     REFERENCES AUTH.ROLE (R_ID_PK);

------------------------------------------------------------------------------------
-- DDL for INDEXES
------------------------------------------------------------------------------------
CREATE INDEX C_ID_PFK_INDX  ON AUTH.CUSTOMER_ROLE (C_ID_PFK);
CREATE INDEX R_ID_PFK_INDX  ON AUTH.CUSTOMER_ROLE (R_ID_PFK);
